from microbit import *
import radio
import random
import time
import os

# generates the device uuid
def get_serial_number(type=hex):
    NRF_FICR_BASE = 0x10000000
    DEVICEID_INDEX = 25  # deviceid[1]

    @micropython.asm_thumb
    def reg_read(r0):
        ldr(r0, [r0, 0])
    return type(reg_read(NRF_FICR_BASE + (DEVICEID_INDEX*4)))

# read the contents of a file on the file system
def getFileContents(fileName):
    try:
        fileToRead = open(fileName)
        fileContents = fileToRead.read()
    except:
        fileContents = ""
    return fileContents

# return the agreed UUID
def getUUID():
    # if the device has a uuid in a file, use it
    # otherwise, use the one generated by the device
    guidLengths = [32, 36, 38, 68] # user defined must these sizes
    thisid = getFileContents("uuid.txt")

    # TODO-maybe: check the GUID sections

    if len(thisid) not in guidLengths:
        thisid = get_serial_number()
    return thisid

# store a uuid in a list and a file
def saveFoundID(foundid):
    if foundid and foundid not in readList:
        readList.append(foundid)
        writelist = ",".join(readList);
        if len(startupData) > 0:
            writelist = "{0},{1}".format(startupData, writelist)
        #for element in readList:
        #    writelist += element
        file = open("data.txt", "w")
        file.write(writelist)
        file.close()
        print("Received: {0}".format(foundid))
    return True

def pauseBroadcast():
    display.show(pauseImage, delay=800, wait=False, loop=True)
    while True:
        print("Pausing broadcast")
        sleep(1000)
        if button_a.was_pressed():
            break
    display.show(heart_beat, delay=800, wait=False, loop=True)
    return True

# setup
display.show(Image.SKULL)
heart_beat = [Image.HEART, Image.HEART_SMALL]
pauseImage = [Image.NO, Image("00000:00000:00000:00000:00000")]
readList = []
uuid = getUUID()
startupData = getFileContents("data.txt")
print("Startup contents = {0}".format(startupData))

# begin
radio.config(group=23)
radio.on()

while True:  # main loop
    print('main loop')
    display.show(heart_beat, delay=800, wait=False, loop=True)

    while True: # inner loop
        if button_a.was_pressed():
            pauseBroadcast()

        radio.send(uuid)
        print("Sent: {0}".format(uuid))

        sleep(1)

        foundid = radio.receive()
        saveFoundID(foundid)
        print("Found {0} other devices since last reset.".format(len(readList)))

        sleep(1000)
    # inner loop
# main loop

# *** General Notes ***
# UUID generation code came from:
# https://support.microbit.org/support/solutions/articles/19000070728-how-to-read-the-device-serial-number

# user generated UUID suggested site:
# https://www.uuidtools.com/

# We will assume any user entered GUID/UUID
# will be in one of the following formats
# 32, 36, 38, 68 character string length ONLY

# 36 characters (Hyphenated)
# 12345678-1234-1234-1234-123456789abc
# 32 characters (Digits only)
# 12345678123412341234123456789abc
# 38 characters (Braces)
# {12345678-1234-1234-1234-123456789abc}
# 38 characters (Parentheses)
# (12345678-1234-1234-1234-123456789abc)
# 68 characters (Hexadecimal)
# {0x12345678,0x1234,0x1234,{0x12,0x34,0x12,0x34,0x56,0x78,0x9a,0xbc}}

# GUID info:
# https://blog.stephencleary.com/2010/11/few-words-on-guids.html